# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e42db0e7025896f44724cf0821833904"
application_url = "https://shopify-announcement-app.onrender.com/"
embedded = true
name = "announcement-bar"
handle = "announcement-bar-26"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes,write_themes"

[auth]
redirect_urls = [
  "https://shopify-announcement-app.onrender.com/auth/callback",
  "https://shopify-announcement-app.onrender.com/auth/shopify/callback",
  "https://shopify-announcement-app.onrender.com/api/auth/callback"
]

[app_proxy]
url = "https://shopify-announcement-app.onrender.com/apps/announcement"
subpath = "announcement"
prefix = "apps"

[pos]
embedded = false
